---
abstract: 'HTML5 application cache manifest file generator'
author:
  - 'Kazuhiro Osawa <yappo {at} shibuya {dot} pl>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML5-Manifest
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Digest::MD5: 0
  File::Spec: 0
resources:
  homepage: http://github.com/yappo/p5-HTML5-Manifest/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/yappo/p5-HTML5-Manifest.git
version: 0.01
